init:
  - git config --global core.autocrlf input
build_script:
  - cmd: build.cmd
test: off
artifacts:
  - path: build\*.nupkg
deploy:
  - provider: NuGet
    api_key:
      secure: zS9xOIG0SGR60W0lHAn0/iKN6WxYKwgqwDQJpmo/NdmHnBvLtG18WvbuLvLp9nau
